name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git docker-compose 

      - name: SonarQube Analysis
        env:
          SONAR_HOST_URL: "https://sonarcloud.io/"
          SONAR_TOKEN: ${{ secrets.SONARQUBE }}
        run: |
          docker run --rm \
            -e SONAR_HOST_URL="$SONAR_HOST_URL" \
            -e SONAR_SCANNER_OPTS="-Dsonar.projectKey=${{ github.event.repository.name }} -Dsonar.organization=caiohenrks -Dsonar.languages=js,Docker,PHP -Dsonar.projectVersion=V${{ github.run_number }}" \
            -e SONAR_TOKEN="$SONAR_TOKEN" \
            -v "$(pwd):/usr/src" \
            sonarsource/sonar-scanner-cli

      - name: Build Docker Image
        run: |
          docker-compose -f ./data_app/docker-compose.yml build
          docker build -t ${{ github.event.repository.name }} -f ./data_app/Dockerfile ./data_app

      - name: Security Image Scan
        run: |
          max_attempts=5
          attempt=1

          # Tague a imagem para o Trivy, caso ainda não tenha sido feito
          docker tag ${{ github.event.repository.name }} $DOCKER_USERNAME/${{ github.event.repository.name }}:latest

          while (( attempt <= max_attempts ))
          do
            echo "Attempt $attempt of $max_attempts..."
            if docker run --rm aquasec/trivy image --exit-code 0 --severity HIGH,CRITICAL --format json ${{ github.event.repository.name }}; then
              echo "Trivy scan completed successfully."
              break
            else
              echo "Attempt $attempt failed. Retrying..."
              ((attempt++))
              sleep 10 
            fi

            if (( attempt > max_attempts )); then
              echo "Failed after $max_attempts attempts."
              exit 1
            fi
          done

      - name: Push to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  # Nome de usuário do Docker Hub
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  # Senha do Docker Hub
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker tag ${{ github.event.repository.name }} $DOCKER_USERNAME/${{ github.event.repository.name }}:latest
          docker push $DOCKER_USERNAME/${{ github.event.repository.name }}:latest
          docker tag ${{ github.event.repository.name }} $DOCKER_USERNAME/${{ github.event.repository.name }}:V${{ github.run_number }}
          docker push $DOCKER_USERNAME/${{ github.event.repository.name }}:V${{ github.run_number }}

      - name: Deploy Application
        run: |
          docker-compose -f ./data_app/docker-compose.yml up -d

      - name: Smoke Test
        run: |
          docker run --rm -v ./postman:/etc/newman -t postman/newman run /etc/newman/${{ github.event.repository.name }}.json -r cli

      - name: Upload Artifacts
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          zip -r ${{ github.event.repository.name }}_${{ github.run_number }}.zip artifacts
          curl -v -u $NEXUS_USERNAME:$NEXUS_PASSWORD --upload-file ${{ github.event.repository.name }}_${{ github.run_number }}.zip http://192.168.50.30:8081/repository/jenkins_artifacts/${{ github.event.repository.name }}_${{ github.run_number }}.zip
