name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git docker-compose 

      - name: SonarQube Analysis
        env:
          SONAR_HOST_URL: "https://sonarcloud.io/"
          SONAR_TOKEN: ${{ secrets.SONARQUBE }}
        run: |
          docker run --rm \
            -e SONAR_HOST_URL="$SONAR_HOST_URL" \
            -e SONAR_SCANNER_OPTS="-Dsonar.projectKey=QRCODE-API -Dsonar.organization=caiohenrks -Dsonar.languages=js,Docker,PHP -Dsonar.projectVersion=V${{ github.run_number }}" \
            -e SONAR_TOKEN="$SONAR_TOKEN" \
            -v "$(pwd):/usr/src" \
            sonarsource/sonar-scanner-cli

      - name: Build Docker Image
        run: |
          docker-compose -f ./data_app/docker-compose.yml build
          docker build -t QRCODE-API -f ./data_app/Dockerfile ./data_app

      - name: Push to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  # Nome de usuário do Docker Hub
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  # Senha do Docker Hub
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker tag QRCODE-API $DOCKER_USERNAME/QRCODE-API:latest
          docker push $DOCKER_USERNAME/QRCODE-API:latest
          docker tag QRCODE-API $DOCKER_USERNAME/QRCODE-API:V${{ github.run_number }}
          docker push $DOCKER_USERNAME/QRCODE-API:V${{ github.run_number }}

      - name: Deploy Application
        run: |
          docker-compose -f ./data_app/docker-compose.yml up -d

      - name: Smoke Test
        run: |
          docker run --rm -v ./postman:/etc/newman -t postman/newman run /etc/newman/QRCODE-API.json -r cli

      - name: Upload Artifacts
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          zip -r QRCODE-API_${{ github.run_number }}.zip artifacts
          curl -v -u $NEXUS_USERNAME:$NEXUS_PASSWORD --upload-file QRCODE-API_${{ github.run_number }}.zip http://192.168.50.30:8081/repository/jenkins_artifacts/QRCODE-API_${{ github.run_number }}.zip
